# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toys',
            new_name='Toy',
        ),
    ]
